### PR TITLE
Improve `RecipeChoice` support

### PR DESCRIPTION
**Pull request by Grabsky**
Opening as draft, as there is more work that have to be done. Please leave some feedback whether you want me to continue that, as I'm concerned recipe loading/registering requires quite a bit of a rewrite.

### SCOPE OF THIS PR
- Add `RecipeChoice.MaterialChoice` support for recipes with no metadata specified.
- Allow users to specify multiple choices for one recipe, as that's something `RecipeChoice` is capable of taking care of, and is supported by datapacks.

```json
{
    "type": "smelting",
    "input": [
        { "material": "minecraft:obsidian" },
        { "material": "minecraft:bedrock" }
    ],
    "result": {
        "material": "minecraft:cooked_cod"
    },
    "experience": 0.35,
    "cooking_time": 200
}
```

### NOTES

Couldn't manage to get this working with `it.multicoredev.mclib.json.GsonHelper`, hence why there is new `Gson` instance created in the `NBTRecipes#loadRecipes` method (temporary solution). That might be entirely on my end, will take a proper look at this soon.

Existing and new functionality has not been fully tested but on the first glance, it works.

As you can see from the diff, we tend to follow different code style practices. I'll make sure to fix that before marking this PR as ready-for-review.

### TO-DO
- [x] Figure out how to re-use `NBTRecipes.GSON` instance.
- [x] Support remaining recipe types. (where applicable)
- [x] Test if everything works as expected.
- [x] Minimze code style difference.
- [x] Add note that in case `MaterialChoice` and `ExactChoice` are mixed together, everything becomes `ExactChoice`.

### CODE REVIEW

**Comment by Grabsky** [comment]
I have just added support for remaining recipe types. Tested with README examples (plain and modified) and they seem to work fine. Also noticed that there is a Bukkit API limitation that doesn't allow both, `MaterialChoice` and `ExactChoice` mixed together. Later I'm going to add an user-friendly note about that to the README page.

For clarity:
```json
{
    "type": "smelting",
    "input": [
        { "material": "minecraft:obsidian" },
        { "material": "minecraft:bedrock", "nbt": "{CustomModelData:1}" }
    ],
    "result": {
        "material": "minecraft:cooked_cod"
    },
    "experience": 0.35,
    "cooking_time": 200
}
```
is not possible and both input values will be treated as `ExactChoice`. It's a niche use-case anyway so I don't think a lot of people is going to be bothered by something like that but regardless, note should be included.

**Comment by LoreSchaeffer** [comment]
I usually use JsonSerializer/JsonDeserializer to create the Adapters and to register it in the GsonHelper class, just add a new it.multicoredev.mclib.json.TypeAdapter instance after the Material one

**Comment by Grabsky** [comment]
Migration to `JsonDeserializer` did fix the issue, I was able to register adapter to the `GsonHelper` class normally, thanks.

I have updated some exception messages to be, hopefully, a bit more helpful in terms of what went wrong and did some improvements to README documentation, including rework of examples. They should be easier to understand now as well as showcase more plugin features.

**Comment by Grabsky** [comment]
Turns out `smithing` recipe type copies base item NBT to the result item NBT, at least that's what I think is happening as previous example was not working properly.

Technically `SmithingPrepareEvent` could be listened to, to correct that behavior, but it's out of scope of this PR. I'd also argue this should be opt-in. For example:
```json5
{
  "type": "smithing",
  "copy_base_nbt_to_result": false, // true by default
  "base": { "material": "iron_pickaxe" },
  "template": { "material": "air" },
  "addition": { "material": "diamond" },
  "result": { "material": "diamond_pickaxe", "nbt": "{CustomModelData:5}" },
}
```
But again, that's something I might be able to work on in a future PR. Not entirely sure if possible without some sort of a trade-off or desync(s). From my own experience I can tell that `AnvilPrepareEvent` was a nightmare to work with, I can expect the same for the `SmithingPrepareEvent`.

**Comment by LoreSchaeffer** [comment]
Hi, thank you for the hard work. Have you tested the plugin with the additions?

**Comment by Grabsky** [comment]
> Hi, thank you for the hard work. Have you tested the plugin with the additions?

Yes, I did test it with no issues found. I'm pretty sure everything works as expected and backwards compatibility is fully preserved.

**Pull request merged**
